// SPDX-License-Identifier: GPL-2.0+

#ifndef __SUNXI_SYS_CONFIG_GPIO_H__
#define __SUNXI_SYS_CONFIG_GPIO_H__

#if CONFIG_IS_ENABLED(AW_GPIO_V4) // Support sun65iw1
#define PIOC_REG_o_CFG0                 (0x80)
#define PIOC_REG_o_CFG1                 (0x84)
#define PIOC_REG_o_CFG2                 (0x88)
#define PIOC_REG_o_CFG3                 (0x8C)
#define PIOC_REG_o_DATA                 (0x90)
#define PIOC_REG_o_DRV0                 (0xa0)
#define PIOC_REG_o_DRV1                 (0xa4)
#define PIOC_REG_o_DRV2                 (0xa8)
#define PIOC_REG_o_DRV3                 (0xac)
#define PIOC_REG_o_PUL0                 (0xb0)
#define PIOC_REG_o_PUL1                 (0xb4)
#define PIOC_o_OFFSET                   (0x80)
#define PIOC_o_DLEVEL                   (8)
#define PIO_CFG_MASK                    (0xF)
#define PIO_DRV_MASK                    (0x3)

#define R_PIOC_REG_o_CFG0                 (0x80)
#define R_PIOC_REG_o_CFG1                 (0x84)
#define R_PIOC_REG_o_CFG2                 (0x88)
#define R_PIOC_REG_o_CFG3                 (0x8C)
#define R_PIOC_REG_o_DATA                 (0x90)
#define R_PIOC_REG_o_DRV0                 (0xa0)
#define R_PIOC_REG_o_DRV1                 (0xa4)
#define R_PIOC_REG_o_DRV2                 (0xa8)
#define R_PIOC_REG_o_DRV3                 (0xac)
#define R_PIOC_REG_o_PUL0                 (0xb0)
#define R_PIOC_REG_o_PUL1                 (0xb4)
#define R_PIOC_o_OFFSET                   (0x80)
#elif CONFIG_IS_ENABLED(AW_GPIO_V3) // Support sun60iw2 sun55iw6
#define PIOC_REG_o_CFG0                 (0x80)
#define PIOC_REG_o_CFG1                 (0x84)
#define PIOC_REG_o_CFG2                 (0x88)
#define PIOC_REG_o_CFG3                 (0x8C)
#define PIOC_REG_o_DATA                 (0x90)
#define PIOC_REG_o_DATA_SET             (0x94)
#define PIOC_REG_o_DATA_CLR             (0x98)
#define PIOC_REG_o_DRV0                 (0xa0)
#define PIOC_REG_o_DRV1                 (0xa4)
#define PIOC_REG_o_DRV2                 (0xa8)
#define PIOC_REG_o_DRV3                 (0xac)
#define PIOC_REG_o_PUL0                 (0xb0)
#define PIOC_REG_o_PUL1                 (0xb4)
#define PIOC_o_OFFSET                   (0x80)
#define PIOC_o_DLEVEL                   (8)
#define PIO_CFG_MASK                    (0xF)
#define PIO_DRV_MASK                    (0x3)

#define R_PIOC_REG_o_CFG0                 (0x0)
#define R_PIOC_REG_o_CFG1                 (0x4)
#define R_PIOC_REG_o_CFG2                 (0x8)
#define R_PIOC_REG_o_CFG3                 (0xC)
#define R_PIOC_REG_o_DATA                 (0x10)
#define R_PIOC_REG_o_DATA_SET             (0x504)
#define R_PIOC_REG_o_DATA_CLR             (0x508)
#define R_PIOC_REG_o_DRV0                 (0x14)
#define R_PIOC_REG_o_DRV1                 (0x18)
#define R_PIOC_REG_o_DRV2                 (0x1c)
#define R_PIOC_REG_o_DRV3                 (0x20)
#define R_PIOC_REG_o_PUL0                 (0x24)
#define R_PIOC_REG_o_PUL1                 (0x28)
#define R_PIOC_o_OFFSET                   (0x30)
#elif CONFIG_IS_ENABLED(SUNXI_GPIO_V2)
#define PIOC_REG_o_CFG0                 (0x00)
#define PIOC_REG_o_CFG1                 (0x04)
#define PIOC_REG_o_CFG2                 (0x08)
#define PIOC_REG_o_CFG3                 (0x0C)
#define PIOC_REG_o_DATA                 (0x10)
#define PIOC_REG_o_DRV0                 (0x14)
#define PIOC_REG_o_DRV1                 (0x18)
#define PIOC_REG_o_DRV2                 (0x1C)
#define PIOC_REG_o_DRV3                 (0x20)
#define PIOC_REG_o_PUL0                 (0x24)
#define PIOC_REG_o_PUL1                 (0x28)
#define PIOC_o_OFFSET			(0x30)
#define PIOC_o_DLEVEL			(8)
#define PIO_CFG_MASK			(0x0f)
#else
#define PIOC_REG_o_CFG0                 (0x00)
#define PIOC_REG_o_CFG1                 (0x04)
#define PIOC_REG_o_CFG2                 (0x08)
#define PIOC_REG_o_CFG3                 (0x0C)
#define PIOC_REG_o_DATA                 (0x10)
#define PIOC_REG_o_DRV0                 (0x14)
#define PIOC_REG_o_DRV1                 (0x18)
#define PIOC_REG_o_PUL0                 (0x1C)
#define PIOC_REG_o_PUL1                 (0x20)
#define PIO_CFG_MASK			(0x07)
#define PIOC_o_OFFSET			(0x24)
#define PIOC_o_DLEVEL			(16)
#endif

#endif /* __SUNXI_SYS_CONFIG_GPIO_H__ */

